[package]
name = "leptonic"
version = "0.2.0-alpha"
edition = "2021"
rust-version = "1.70.0"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptonic"
description = """
The Leptos component library.
"""
categories = ["gui"]
keywords = ["leptos", "components", "component-library"]

[dependencies]
indexmap = "2.0.0"
js-sys = "0.3.64"
leptos = { version = "0.5.0-alpha", features = ["csr"] }
leptos-tiptap = "0.3.0-alpha"
#leptos-use = { version = "0.6.0", features = ["math"] }
leptos-use = { git = "https://github.com/Synphonyte/leptos-use", branch = "main", features = ["math"] }
leptos_icons = { version = "0.0.16-alpha", features = [
    "BsSun",
    "BsMoon",
    "BsCheckCircleFill",
    "BsInfoCircleFill",
    "BsExclamationCircleFill",
    "BsExclamationTriangleFill",
    "BsCaretUp",
    "BsCaretUpFill",
    "BsCaretDown",
    "BsCaretDownFill",
    "BsParagraph",
    "BsTypeBold",
    "BsTypeItalic",
    "BsTypeStrikethrough",
    "BsBlockquoteLeft",
    "BsBrightnessAltHigh",
    "BsTextLeft",
    "BsTextCenter",
    "BsTextRight",
    "BsJustify",
    "BsXCircleFill",
] }
leptos_router = "0.5.0-alpha"
serde = "1.0.171"
serde-wasm-bindgen = "0.5.0"
serde_json = "1.0.103"
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3.23", features = [
    "wasm-bindgen",
    "macros",
    "serde",
    "serde-well-known",
] }
tracing = "0.1.37"
uuid = { version = "1.4.0", features = ["v4", "v7", "js", "serde"] }
wasm-bindgen = "0.2.87"
# TODO: What of all below is really required?
web-sys = { version = "0.3.64", features = [
    "DomRect",
    "Event",
    "EventTarget",
    "HtmlFormElement",
    "HtmlInputElement",
    "Storage",
] }

[dev-dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-test = "0.3.37"
web-sys = "0.3.64"
