[package]
name = "book"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.release]
opt-level = "z"
lto = "fat"
debug = 0

[dependencies]
console_error_panic_hook = "0.1.7"
indoc = "2.0.1"
leptonic = { path = "../../leptonic" }
leptos = { version = "0.5.0-alpha", features = ["csr"] }
#leptos-use = "0.6.0"
leptos-use = { git = "https://github.com/Synphonyte/leptos-use", branch = "main" }
leptos_icons = { version = "0.0.16-alpha", features = [
    "BsGithub",
    "BsSearch",
    "BsList",
    "BsThreeDots",
    "BsFolder",
    "BsFolderFill",
    "BsBook",
    "BsColumnsGap",
    "BsToggles",
    "BsChatSquare",
    "BsCircleSquare",
    "BsArrowsMove",
    "BsVolumeDownFill",
    "BsVolumeUpFill",
    "BsBell",
    "BsPower",
] }
leptos_meta = { version = "0.5.0-alpha", features = ["csr"] }
leptos_router = { version = "0.5.0-alpha", features = ["csr"] }
serde = "1.0.171"
serde-wasm-bindgen = "0.5.0"
serde_json = "1.0.103"
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3.23", features = ["wasm-bindgen"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
uuid = { version = "1.4.0", features = ["js", "v4", "v7", "serde"] }
wasm-bindgen = "0.2.87"

[build-dependencies]
leptonic-theme = { path = "../../leptonic-theme" }
leptos-tiptap-build = "0.2.0"
